# Template for training configuration
# Use this as a starting point for defining training jobs.

dataset: path/to/dataset
model: yolov5nu
epochs: 300
batch_size: 32
optimizer: SGD
lr_schedule: cosine
augmentations:
  - mosaic
  - mixup
